# Etapa 1: Construcción de la aplicación
FROM node:16 AS builder

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos package.json y package-lock.json
COPY package.json package-lock.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto del código fuente
COPY . .

# Construir la aplicación para producción
RUN npm run build

# Etapa 2: Imagen para producción
FROM nginx:alpine

# Copiar los archivos de construcción al contenedor de nginx
COPY --from=builder /app/build /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80

# Usar nginx para servir la aplicación
CMD ["nginx", "-g", "daemon off;"]
